### ISSUE TITLE
TODO v0.2

### ISSUE THREAD

**Issue by LeonardoBentolila** [LeonardoBentolila/easy-zip#1]
TODO: 
- [ ] ask if want to override existing output zip file
- [ ] add option to receive multiple target folders  
- [ ] cleaner print messages 
- [ ] list files with recursive function using glob("*") to give better feedback during process
